# /srv/clickhouse/docker-compose.yml
version: "3.8"
services:
  clickhouse:
    image: clickhouse/clickhouse-server:24.3
    user: "1002:1002"
    volumes:
      - /srv/clickhouse/data:/var/lib/clickhouse
      - /srv/clickhouse/config:/etc/clickhouse-server
      - /srv/clickhouse/logs:/var/log/clickhouse-server
    environment:
      CLICKHOUSE_DB: dwh
      CLICKHOUSE_USER: dwhapp
      CLICKHOUSE_PASSWORD: UltraStr0ngPW
    ports:
      - "8123:8123"
      - "9000:9000"
      - "9009:9009"
    networks:
      - dwh_net
    ulimits:
      nofile:
        soft: 262144
        hard: 262144

networks:
  dwh_net:
    external: true
