# roles/airflow/tasks/main.yml (same pattern)

- name: Create Airflow directories
  file:
    path: "/srv/airflow/{{ item }}"
    state: directory
    owner: airflow
    group: airflow
    mode: '0755'
  with_items:
    - dags
    - logs
    - plugins
    - pgdata

- name: Deploy Airflow docker-compose
  copy:
    dest: /srv/airflow/docker-compose.yml
    content: |
      version: "3.8"
      services:
        postgres:
          image: postgres:16
          environment:
            POSTGRES_USER: airflow
            POSTGRES_PASSWORD: "{{ airflow_db_password }}"
            POSTGRES_DB: airflow
          volumes:
            - /srv/airflow/pgdata:/var/lib/postgresql/data
          networks:
            - {{ dwh_docker_network }}

        airflow-webserver:
          image: apache/airflow:2.9.0
          user: "1005:1005"
          depends_on:
            - postgres
          environment:
            AIRFLOW__CORE__EXECUTOR: LocalExecutor
            AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:{{ airflow_db_password }}@postgres/airflow
          volumes:
            - /srv/airflow/dags:/opt/airflow/dags
            - /srv/airflow/logs:/opt/airflow/logs
            - /srv/airflow/plugins:/opt/airflow/plugins
          ports:
            - "8080:8080"
          networks:
            - {{ dwh_docker_network }}
      networks:
        {{ dwh_docker_network }}:
          external: true

- name: Start Airflow with docker-compose
  shell: docker compose -f /srv/airflow/docker-compose.yml up -d
  args:
    chdir: /srv/airflow
