# roles/minio/tasks/main.yml

- name: Create MinIO directories
  file:
    path: "/srv/minio/{{ item }}"
    state: directory
    owner: minio
    group: minio
    mode: '0755'
  with_items:
    - data
    - config

- name: Ensure MinIO docker-compose file exists
  copy:
    dest: /srv/minio/docker-compose.yml
    content: |
      version: "3.8"
      services:
        minio:
          image: minio/minio:RELEASE.2024-06-01T00-00-00Z
          user: "1001:1001"
          volumes:
            - /srv/minio/data:/data
            - /srv/minio/config:/root/.minio
          ports:
            - "{{ minio_api_port }}:9000"
            - "{{ minio_console_port }}:9001"
          environment:
            MINIO_ROOT_USER: "{{ minio_access_key }}"
            MINIO_ROOT_PASSWORD: "{{ minio_secret_key }}"
            MINIO_SERVER_URL: "http://{{ inventory_hostname }}:9000"
          command: server /data --console-address ":9001"
          restart: always
          networks:
            - {{ dwh_docker_network }}
      networks:
        {{ dwh_docker_network }}:
          external: true

- name: Create docker network if not present
  shell: docker network inspect {{ dwh_docker_network }} || docker network create {{ dwh_docker_network }}
  args:
    warn: false

- name: Start MinIO with docker-compose
  shell: docker compose -f /srv/minio/docker-compose.yml up -d
  args:
    chdir: /srv/minio
